-- Minimal analytics table for page views and admin login attempts
create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('page_view', 'admin_login')),
  status text null check (status in ('success', 'failed')),
  route_path text null,
  email text null,
  source text null check (source in ('mock', 'supabase')),
  user_agent text null,
  created_at timestamptz not null default now()
);

alter table public.analytics_events enable row level security;

-- App only needs insert rights for basic tracking.
drop policy if exists "analytics_insert_policy" on public.analytics_events;
create policy "analytics_insert_policy"
on public.analytics_events
for insert
to anon, authenticated
with check (
  event_type in ('page_view', 'admin_login')
);

-- Optional: allow authenticated users to read logs from SQL editor/client tools.
drop policy if exists "analytics_select_auth" on public.analytics_events;
create policy "analytics_select_auth"
on public.analytics_events
for select
to authenticated
using (true);

create index if not exists idx_analytics_events_created_at on public.analytics_events(created_at desc);
create index if not exists idx_analytics_events_event_type on public.analytics_events(event_type);
